export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
};

export const ROLE_HIERARCHY = {
  [ROLES.OWNER]: 5,
  [ROLES.ADMIN]: 4,
  [ROLES.MANAGER]: 3,
  [ROLES.MEMBER]: 2,
  [ROLES.VIEWER]: 1,
};

export const PERMISSIONS = {
  // Workspace permissions
  WORKSPACE_UPDATE: 'workspace:update',
  WORKSPACE_DELETE: 'workspace:delete',
  WORKSPACE_TRANSFER: 'workspace:transfer',
  WORKSPACE_INVITE_MEMBER: 'workspace:invite_member',
  WORKSPACE_REMOVE_MEMBER: 'workspace:remove_member',
  WORKSPACE_UPDATE_ROLE: 'workspace:update_role',
  WORKSPACE_VIEW: 'workspace:view',

  // Project permissions
  PROJECT_CREATE: 'project:create',
  PROJECT_UPDATE: 'project:update',
  PROJECT_DELETE: 'project:delete',
  PROJECT_MANAGE_MEMBERS: 'project:manage_members',
  PROJECT_VIEW: 'project:view',

  // Task permissions
  TASK_CREATE: 'task:create',
  TASK_UPDATE: 'task:update',
  TASK_DELETE: 'task:delete',
  TASK_MOVE: 'task:move',
  TASK_ASSIGN: 'task:assign',
  TASK_COMMENT: 'task:comment',
  TASK_VIEW: 'task:view',

  // Chat permissions
  CHANNEL_CREATE: 'channel:create',
  CHANNEL_UPDATE: 'channel:update',
  CHANNEL_DELETE: 'channel:delete',
  MESSAGE_SEND: 'message:send',
  MESSAGE_DELETE_ANY: 'message:delete_any',

  // File permissions
  FILE_UPLOAD: 'file:upload',
  FILE_DELETE_ANY: 'file:delete_any',

  // Analytics
  ANALYTICS_VIEW: 'analytics:view',
};

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_INVITE_MEMBER,
    PERMISSIONS.WORKSPACE_REMOVE_MEMBER,
    PERMISSIONS.WORKSPACE_UPDATE_ROLE,
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_MOVE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.CHANNEL_CREATE,
    PERMISSIONS.CHANNEL_UPDATE,
    PERMISSIONS.CHANNEL_DELETE,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.MESSAGE_DELETE_ANY,
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.FILE_DELETE_ANY,
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.WORKSPACE_INVITE_MEMBER,
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_MOVE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.CHANNEL_CREATE,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_MOVE,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
};

export const hasPermission = (userRole, requiredPermission) => {
  if (!userRole) return false;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(requiredPermission);
};

